services:
  postgres:
    image: 'postgres:16-alpine'
    environment:
      - 'POSTGRES_DB=eventdb'
      - 'POSTGRES_PASSWORD=geheim123'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
